### ISSUE TITLE
deprecated method "wn.on()" ?

### ISSUE THREAD

**Issue by miccferr** [hughrawlinson/wekinator-node#1]
Hi there,

first of all thanks for the awesome library to interact with Wekinator!

I just want to mention that in the `examples/index.js` there's a method which I believe is no longer supported: `wn.on()` (see [here for reference](https://github.com/hughrawlinson/wekinator-node/blob/master/examples/index.js#L15) ).

If that's the case, is there a substitute? Or `ws` automatically registers a handle for incoming messages?

Cheers!

**Comment by mattpen** [comment]
I had trouble with this method running Node 4.x/Windows 10, but it is working for me as expected on Node 0.10.x/Linux Mint.  There may be some incompatibility with Windows or Node 4.x.

**Comment by hughrawlinson** [comment]
I'm so sorry I missed both of these!

@mattpen yes, it looks like my examples are out of sync with the implementation, I'll have a look at fixing that and writing better docs.

@mattpen I don't have a windows machine so I can't test, but I would imagine that this is an issue with the [osc](https://www.npmjs.com/package/osc) library, which I depend on, and if you're still interested in getting this running on Windows I'd recommend building a repro for them and seeing if they can have a look at it.

**Comment by hughrawlinson** [comment]
@miccferr just to address this issue directly:

The on method is registered after you call connect. You'd need to do something like:

```js
const wn = require('wekinator');
wn();
wn.connect();
wn.on(console.log);
```

but `wn.on` won't be defined until after you actually call connect.
