### ISSUE TITLE
Jest Timer API Update

### ISSUE THREAD

**Issue by hughrawlinson** [hughrawlinson/wekinator-node#65]
Jest [have changed](https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers) their default timer API to "modern" from "legacy", and so #70 fails - rather than just using the legacy timer API, we should take this opportunity to update our tests to use the modern timer API.

**Comment by hionnode** [comment]
Can I take this up ?

**Comment by hughrawlinson** [comment]
Absolutely, @hionnode!
